on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      arg_name:
        description: '镜像名称,完整标签, nginx:latest'
        required: true
        default: ''
      arg_aliyunurl:
        description: 'githubcr地址: '
        required: true
        default: 'ghcr.io'
      arg_aliyunuser:
        description: 'github用户名: '
        required: true
        default: 'jcleng'

name: build images && push
jobs:
  buildimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ github.event.inputs.arg_aliyunurl }}
        username: ${{ github.event.inputs.arg_aliyunuser }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: build images
      run: |
        docker build . -t ${{ github.event.inputs.arg_aliyunurl }}/${{ github.event.inputs.arg_aliyunuser }}/${{ github.event.inputs.arg_name }}
        docker push ${{ github.event.inputs.arg_aliyunurl }}/${{ github.event.inputs.arg_aliyunuser }}/${{ github.event.inputs.arg_name }}

    - name: Release set path
      run: |
        touch release.txt
        echo ${{ github.event.inputs.arg_aliyunurl }}/${{ github.event.inputs.arg_aliyunuser }}/${{ github.event.inputs.arg_name }} >> release.txt

    - name: Generate valid tag name
      run: |
        TAG_NAME=$(echo $TAG_NAME | sed 's/:/_/g')
        echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
      env:
        TAG_NAME: ${{ github.event.inputs.arg_name }}

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag_name }}
        body_path: release.txt
        files: release.txt
